medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      dbname: medical_warehouse
      schema: analytics
      user: postgres
      password: "MoGGy8080"
      threads: 4
